const ACTION_TYPES = {
  CONNECTION_ESTABLISHED: 'CONNECTION_ESTABLISHED',
  USER_JOINED: 'USER_JOINED',
  USER_LEFT: 'USER_LEFT',
  MESSAGE_SENT: 'MESSAGE_SENT',
};

module.exports = { ACTION_TYPES };
